Add system dependencies to build instructions
setzer22/blackjack pull request #57
Opened 2022-10-31 02:31 UTC by HenryWConklin

Resolves #56

2022-11-03 18:12 UTC, setzer22 requested changes
Thanks for sending the PR :+1:  A couple minor things:

2022-11-03 18:12 UTC, setzer22 commented on README.md
> +   * Ubuntu/Debian: `sudo apt install libfontconfig-dev`
Could you please add a couple more popular distros? The package seems to be called `fontconfig` on Arch, and `fontconfig-devel` on Fedora.

Also a note stating that these may not be all the missing system dependencies, and asking people to file in a PR if they find any other one.

2022-11-03 18:12 UTC, setzer22 commented on README.md
> +3. From the same folder, run `cargo run --bin blackjack_ui` to launch Blackjack.
While we're at it, could you please change the run command to `cargo run --release --bin blackjack_ui`. Users should run this on release mode (even though debug mode works fine for many use cases).

2022-11-04 00:40 UTC, HenryWConklin commented on README.md
> +   * Ubuntu/Debian: `sudo apt install libfontconfig-dev`
Added, hopefully I got those commands right I'm not too familiar with other distros.

2022-11-04 00:40 UTC, HenryWConklin commented on README.md
> +3. From the same folder, run `cargo run --bin blackjack_ui` to launch Blackjack.
Added.

2022-11-04 09:06 UTC, setzer22 approved these changes
Awesome, thanks again for the PR :)  will merge once CI passes

2022-11-04 10:35 UTC, setzer22 commented on README.md
> +
Let's add a reference to the issue here:
```suggestion
> **Note**: The `fontconfig` native dependency is temporary, and will no longer be necessary once this upstream issue is fixed: https://github.com/rust-windowing/winit/issues/2373
```

2022-11-04 10:35 UTC, setzer22 approved these changes

2022-11-04 10:35 UTC, merged