new primitive: points grid
setzer22/blackjack pull request #69
Opened 2022-11-10 13:08 UTC by Zireael07

Title

![Screenshot_20221110_140135](https://user-images.githubusercontent.com/4525388/201099163-b6a680d6-6349-49b3-89a3-3e43863c93e2.jpeg)

5 nodes total, and the ability to preview at any stage of the generation, outputs what is practically equivalent to what took me many months of coding in Godot (because I had to figure out how to use the mesh procedural generation classes, how to create a triangle, a quad, how to subdivide etc.). One more node to give some faces a separate material and then some fiddling with an optional storefront would do the rest...

2022-11-10 17:27 UTC, setzer22 requested changes
Nice work! Just a few changes and it's ready to merge :smile:

2022-11-10 17:27 UTC, setzer22 commented on blackjack_engine/src/mesh/halfedge/primitives.rs
> +        drop(pos);
Unless rust complains about your code, these lines aren't needed. These manual drops are required sometimes when using mesh channels, but I don't think they are in this case because the borrow guards will be automatically dropped at the end of the scope and you're not doing anything else with the mesh afterwards.

Generally in Rust you will not leak memory by forgetting to call `drop` or deallocate objects like in other languages :slightly_smiling_face:

2022-11-10 17:27 UTC, setzer22 commented on blackjack_engine/src/mesh/halfedge/primitives.rs
> +            conn.alloc_vertex(&mut pos, v, None);
Wouldn't it make more sense to call `conn.alloc_vertex` directly on the first loop? That way you save the allocation for the `vertices` vec.

2022-11-11 08:26 UTC, Zireael07 commented on blackjack_engine/src/mesh/halfedge/primitives.rs
> +        drop(pos);
It complains about move of mesh on the final line (mesh) if those lines aren't present.

2022-11-11 08:47 UTC, setzer22 approved these changes
Nice! I think this is ready to merge now. I just checked and I realized those calls to `drop` were actually required :sweat_smile:

2022-11-11 08:47 UTC, merged